package com.example.demo.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestParam;

import com.example.demo.dto.JHRequestDto;
import com.example.demo.service.JHService;

@Controller
public class JHController2 {

    @Autowired
    private JHService jhService;

    @GetMapping("/apichatTest")
    public String handleChatRequest(@RequestParam(value = "query", required = false) String query, Model model) {
        // 질문이 없는 경우, 기본 page05 표시 (또는 page04로 리다이렉트도 가능)
        if (query == null || query.trim().isEmpty()) {
             model.addAttribute("aiResponse", "질문을 입력해주세요."); // 기본 메시지 설정
            return "apichatTest01"; 
        }
        
        String arealist = "[{\r\n"
        		+ "            \"addr1\": \"대구광역시 동구 서촌로23길 13-11\",\r\n"
        		+ "            \"addr2\": \"(덕곡동)\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2745657\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20210916003749\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/90/2746190_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/90/2746190_image2_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6205183884\",\r\n"
        		+ "            \"mapy\": \"35.9841102996\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240729165300\",\r\n"
        		+ "            \"sigungucode\": \"4\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가마솥에 누른 밥\",\r\n"
        		+ "            \"zipcode\": \"41000\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달서구 월배로83길 7\",\r\n"
        		+ "            \"addr2\": \"(송현동)\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020400\",\r\n"
        		+ "            \"contentid\": \"2737976\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20210831194841\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/28/2738128_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/28/2738128_image2_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5513370740\",\r\n"
        		+ "            \"mapy\": \"35.8314957531\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240805000001\",\r\n"
        		+ "            \"sigungucode\": \"2\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가야성\",\r\n"
        		+ "            \"zipcode\": \"42739\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 동구 팔공산로199길 6-3\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2846092\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20220830151646\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/81/2846081_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/81/2846081_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6968281408\",\r\n"
        		+ "            \"mapy\": \"35.9906776367\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240220145622\",\r\n"
        		+ "            \"sigungucode\": \"4\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가원식당\",\r\n"
        		+ "            \"zipcode\": \"41007\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"C01\",\r\n"
        		+ "            \"cat2\": \"C0112\",\r\n"
        		+ "            \"cat3\": \"C01120001\",\r\n"
        		+ "            \"contentid\": \"1873302\",\r\n"
        		+ "            \"contenttypeid\": \"25\",\r\n"
        		+ "            \"createdtime\": \"20131218233155\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/24/1573824_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/24/1573824_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5189157802\",\r\n"
        		+ "            \"mapy\": \"35.8007847438\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20230810145354\",\r\n"
        		+ "            \"sigungucode\": \"2\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가족들 웃음소리 가득 찬 하루\",\r\n"
        		+ "            \"zipcode\": \"\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 서구 문화로 122 (이현동)\",\r\n"
        		+ "            \"addr2\": \"청소년수련관 앞 이현공원\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A02\",\r\n"
        		+ "            \"cat2\": \"A0207\",\r\n"
        		+ "            \"cat3\": \"A02070200\",\r\n"
        		+ "            \"contentid\": \"2397299\",\r\n"
        		+ "            \"contenttypeid\": \"15\",\r\n"
        		+ "            \"createdtime\": \"20160808200930\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/70/3333670_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/70/3333670_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5455030841\",\r\n"
        		+ "            \"mapy\": \"35.8736658721\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240806175831\",\r\n"
        		+ "            \"sigungucode\": \"6\",\r\n"
        		+ "            \"tel\": \"053-663-2181\",\r\n"
        		+ "            \"title\": \"가족사랑 아이스축제\",\r\n"
        		+ "            \"zipcode\": \"41759\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창면 가창로 1099\",\r\n"
        		+ "            \"addr2\": \"(가창면)\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"0\",\r\n"
        		+ "            \"cat1\": \"A02\",\r\n"
        		+ "            \"cat2\": \"A0203\",\r\n"
        		+ "            \"cat3\": \"A02030600\",\r\n"
        		+ "            \"contentid\": \"2034446\",\r\n"
        		+ "            \"contenttypeid\": \"12\",\r\n"
        		+ "            \"createdtime\": \"20151021001307\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/70/1876170_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/70/1876170_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6222232980\",\r\n"
        		+ "            \"mapy\": \"35.8027142041\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20241018165914\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창 찐빵 골목\",\r\n"
        		+ "            \"zipcode\": \"42933\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창면 단산1길 47-1\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A03\",\r\n"
        		+ "            \"cat2\": \"A0302\",\r\n"
        		+ "            \"cat3\": \"A03021700\",\r\n"
        		+ "            \"contentid\": \"2753101\",\r\n"
        		+ "            \"contenttypeid\": \"28\",\r\n"
        		+ "            \"createdtime\": \"20211006002817\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/94/2799794_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/94/2799794_image2_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6631066775\",\r\n"
        		+ "            \"mapy\": \"35.7715573693\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240613100935\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창글램핑장\",\r\n"
        		+ "            \"zipcode\": \"42939\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창면 가창로10길 56\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A03\",\r\n"
        		+ "            \"cat2\": \"A0302\",\r\n"
        		+ "            \"cat3\": \"A03021700\",\r\n"
        		+ "            \"contentid\": \"2740978\",\r\n"
        		+ "            \"contenttypeid\": \"28\",\r\n"
        		+ "            \"createdtime\": \"20210907222827\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/53/2741253_image2_1.JPG\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/53/2741253_image2_1.JPG\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6791981643\",\r\n"
        		+ "            \"mapy\": \"35.7270682494\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240521094320\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창농원글램핑오토캠핑장\",\r\n"
        		+ "            \"zipcode\": \"42940\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창로119길 13\",\r\n"
        		+ "            \"addr2\": \"1층\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2841662\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20220823140651\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/51/2841651_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/51/2841651_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6493913845\",\r\n"
        		+ "            \"mapy\": \"35.7655411302\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240221144900\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창닭갈비\",\r\n"
        		+ "            \"zipcode\": \"42939\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창로175길 14\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2851723\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20220907174337\",\r\n"
        		+ "            \"firstimage\": \"\",\r\n"
        		+ "            \"firstimage2\": \"\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"\",\r\n"
        		+ "            \"mapx\": \"128.6373668267\",\r\n"
        		+ "            \"mapy\": \"35.7877134014\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250115142545\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창숯불갈비\",\r\n"
        		+ "            \"zipcode\": \"42938\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창면 가창로108길 7\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A03\",\r\n"
        		+ "            \"cat2\": \"A0302\",\r\n"
        		+ "            \"cat3\": \"A03020300\",\r\n"
        		+ "            \"contentid\": \"3014114\",\r\n"
        		+ "            \"contenttypeid\": \"28\",\r\n"
        		+ "            \"createdtime\": \"20230824152345\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/70/3014070_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/70/3014070_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6526856420\",\r\n"
        		+ "            \"mapy\": \"35.7618332761\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20241113171925\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"가창실내테니스장\",\r\n"
        		+ "            \"zipcode\": \"42939\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달서구 조암로 58\",\r\n"
        		+ "            \"addr2\": \"(월성동)\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2766502\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20211102201103\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/23/2766623_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/23/2766623_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5237091503\",\r\n"
        		+ "            \"mapy\": \"35.8243321674\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250317131548\",\r\n"
        		+ "            \"sigungucode\": \"2\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"갈비만 대구본점\",\r\n"
        		+ "            \"zipcode\": \"42754\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 우록3길 73\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2841682\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20220823141216\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/66/2841666_image2_1.png\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/66/2841666_image3_1.png\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6367549604\",\r\n"
        		+ "            \"mapy\": \"35.7166964170\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250116103417\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"감나무집\",\r\n"
        		+ "            \"zipcode\": \"42940\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 서구 서대구로3길 43\",\r\n"
        		+ "            \"addr2\": \"(내당동)\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"0\",\r\n"
        		+ "            \"cat1\": \"A02\",\r\n"
        		+ "            \"cat2\": \"A0202\",\r\n"
        		+ "            \"cat3\": \"A02020700\",\r\n"
        		+ "            \"contentid\": \"1118418\",\r\n"
        		+ "            \"contenttypeid\": \"12\",\r\n"
        		+ "            \"createdtime\": \"20101028191433\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/87/2493687_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/87/2493687_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5522334637\",\r\n"
        		+ "            \"mapy\": \"35.8586426972\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250318190326\",\r\n"
        		+ "            \"sigungucode\": \"6\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"감삼못공원\",\r\n"
        		+ "            \"zipcode\": \"41856\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 북구 서변동\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A03\",\r\n"
        		+ "            \"cat2\": \"A0302\",\r\n"
        		+ "            \"cat3\": \"A03020300\",\r\n"
        		+ "            \"contentid\": \"3089910\",\r\n"
        		+ "            \"contenttypeid\": \"28\",\r\n"
        		+ "            \"createdtime\": \"20230824104510\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/02/3089902_image2_1.JPG\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/02/3089902_image3_1.JPG\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5903731451\",\r\n"
        		+ "            \"mapy\": \"35.9090182510\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250408142839\",\r\n"
        		+ "            \"sigungucode\": \"5\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"강변축구장\",\r\n"
        		+ "            \"zipcode\": \"41480\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 가창면 가창로176길 18\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2766724\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20211102230134\",\r\n"
        		+ "            \"firstimage\": \"\",\r\n"
        		+ "            \"firstimage2\": \"\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"\",\r\n"
        		+ "            \"mapx\": \"128.6360085440\",\r\n"
        		+ "            \"mapy\": \"35.7901992065\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20241223190005\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"강원도집\",\r\n"
        		+ "            \"zipcode\": \"42938\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 다사읍 강정본길 57\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"0\",\r\n"
        		+ "            \"cat1\": \"A02\",\r\n"
        		+ "            \"cat2\": \"A0202\",\r\n"
        		+ "            \"cat3\": \"A02020700\",\r\n"
        		+ "            \"contentid\": \"2704116\",\r\n"
        		+ "            \"contenttypeid\": \"12\",\r\n"
        		+ "            \"createdtime\": \"20210118230415\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/56/3347856_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/56/3347856_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.4650416326\",\r\n"
        		+ "            \"mapy\": \"35.8411597415\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20250319165219\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"강정고령보\",\r\n"
        		+ "            \"zipcode\": \"42917\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 중구 동성로 36-6\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"634155\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20081009012459\",\r\n"
        		+ "            \"firstimage\": \"\",\r\n"
        		+ "            \"firstimage2\": \"\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"\",\r\n"
        		+ "            \"mapx\": \"128.5942793581\",\r\n"
        		+ "            \"mapy\": \"35.8730779485\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20241202105614\",\r\n"
        		+ "            \"sigungucode\": \"8\",\r\n"
        		+ "            \"tel\": \"053-422-0366\",\r\n"
        		+ "            \"title\": \"개정\",\r\n"
        		+ "            \"zipcode\": \"41938\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 동구 동부로 149\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A04\",\r\n"
        		+ "            \"cat2\": \"A0401\",\r\n"
        		+ "            \"cat3\": \"A04011000\",\r\n"
        		+ "            \"contentid\": \"2929314\",\r\n"
        		+ "            \"contenttypeid\": \"38\",\r\n"
        		+ "            \"createdtime\": \"20221030170846\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/62/2883862_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/62/2883862_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.6292150324\",\r\n"
        		+ "            \"mapy\": \"35.8779835934\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240323140058\",\r\n"
        		+ "            \"sigungucode\": \"4\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"갤럭시라이프스타일 신세계 대구점\",\r\n"
        		+ "            \"zipcode\": \"41229\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 중구 달구벌대로 2077\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A04\",\r\n"
        		+ "            \"cat2\": \"A0401\",\r\n"
        		+ "            \"cat3\": \"A04011000\",\r\n"
        		+ "            \"contentid\": \"2917487\",\r\n"
        		+ "            \"contenttypeid\": \"38\",\r\n"
        		+ "            \"createdtime\": \"20221030204210\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/95/2883995_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/95/2883995_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5906548560\",\r\n"
        		+ "            \"mapy\": \"35.8666702733\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240323134306\",\r\n"
        		+ "            \"sigungucode\": \"8\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"갤럭시라이프스타일 현대 대구점\",\r\n"
        		+ "            \"zipcode\": \"41936\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 북구 옥산로 53\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020100\",\r\n"
        		+ "            \"contentid\": \"2866153\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20221012132635\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/44/2866144_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/44/2866144_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.5814829152\",\r\n"
        		+ "            \"mapy\": \"35.8855735199\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240620171450\",\r\n"
        		+ "            \"sigungucode\": \"5\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"걸리버막창\",\r\n"
        		+ "            \"zipcode\": \"41589\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 중구 동성로5길 22\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A04\",\r\n"
        		+ "            \"cat2\": \"A0401\",\r\n"
        		+ "            \"cat3\": \"A04011000\",\r\n"
        		+ "            \"contentid\": \"2915123\",\r\n"
        		+ "            \"contenttypeid\": \"38\",\r\n"
        		+ "            \"createdtime\": \"20221101071011\",\r\n"
        		+ "            \"firstimage\": \"\",\r\n"
        		+ "            \"firstimage2\": \"\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"\",\r\n"
        		+ "            \"mapx\": \"128.5957210462\",\r\n"
        		+ "            \"mapy\": \"35.8677313587\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240324141503\",\r\n"
        		+ "            \"sigungucode\": \"8\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"게스 동성로\",\r\n"
        		+ "            \"zipcode\": \"41942\"\r\n"
        		+ "          },\r\n"
        		+ "          {\r\n"
        		+ "            \"addr1\": \"대구광역시 달성군 강정본길 77\",\r\n"
        		+ "            \"addr2\": \"\",\r\n"
        		+ "            \"areacode\": \"4\",\r\n"
        		+ "            \"booktour\": \"\",\r\n"
        		+ "            \"cat1\": \"A05\",\r\n"
        		+ "            \"cat2\": \"A0502\",\r\n"
        		+ "            \"cat3\": \"A05020900\",\r\n"
        		+ "            \"contentid\": \"2841697\",\r\n"
        		+ "            \"contenttypeid\": \"39\",\r\n"
        		+ "            \"createdtime\": \"20220823141859\",\r\n"
        		+ "            \"firstimage\": \"http://tong.visitkorea.or.kr/cms/resource/88/2841688_image2_1.jpg\",\r\n"
        		+ "            \"firstimage2\": \"http://tong.visitkorea.or.kr/cms/resource/88/2841688_image3_1.jpg\",\r\n"
        		+ "            \"cpyrhtDivCd\": \"Type3\",\r\n"
        		+ "            \"mapx\": \"128.4635722847\",\r\n"
        		+ "            \"mapy\": \"35.8423623562\",\r\n"
        		+ "            \"mlevel\": \"6\",\r\n"
        		+ "            \"modifiedtime\": \"20240730225236\",\r\n"
        		+ "            \"sigungucode\": \"3\",\r\n"
        		+ "            \"tel\": \"\",\r\n"
        		+ "            \"title\": \"게이블루프커피\",\r\n"
        		+ "            \"zipcode\": \"42917\"\r\n"
        		+ "          }]";
        // DTO 생성
        JHRequestDto requestDto = new JHRequestDto();
        requestDto.setMessage(query);
        requestDto.setArealistrq(arealist);
        
        // FastAPI 서비스 호출
        String response = jhService.getJHResponse(requestDto);
        
        // 모델에 데이터 추가
        model.addAttribute("query", query);
        model.addAttribute("aiResponse", response); 
        
        // 결과 페이지인 "page05"를 반환
        return "apichatTest01";
    }
}